using System.Reflection;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyConfigurationAttribute("release")]
[assembly: AssemblyCompanyAttribute("http://nantcontrib.sourceforge.net")]
[assembly: AssemblyProductAttribute("NAntContrib")]
[assembly: AssemblyCopyrightAttribute("Copyright (C) 2001-2011 Gerry Shaw")]
[assembly: AssemblyTrademarkAttribute("")]
[assembly: AssemblyCultureAttribute("")]
[assembly: AssemblyVersionAttribute("0.91.4312.0")]
[assembly: AssemblyInformationalVersionAttribute("0.91")]

