using System.Reflection;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyConfigurationAttribute("rc4")]
[assembly: AssemblyCompanyAttribute("http://nantcontrib.sourceforge.net")]
[assembly: AssemblyProductAttribute("NAntContrib")]
[assembly: AssemblyCopyrightAttribute("Copyright (C) 2001-2006 Gerry Shaw")]
[assembly: AssemblyTrademarkAttribute("")]
[assembly: AssemblyCultureAttribute("")]
[assembly: AssemblyVersionAttribute("0.85.2344.0")]
[assembly: AssemblyInformationalVersionAttribute("0.85")]

